import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,readFile,writeFile,rm,symlink,chmod}from'node:fs/promises';import path from'node:path';import os from'node:os';import {consumeHandoff,SECRET_NAME}from'../src/handoff.mjs';
async function fixture(fn){const root=await mkdtemp(path.join(os.tmpdir(),'ocg-handoff-'));const values=new Map();const secrets={async store(k,v){values.set(k,v);},async get(k){return values.get(k);},async delete(k){values.delete(k);}};const input={schemaVersion:1,operation:'connect',connectionId:'8b68d24b-15dc-4a7d-bb3d-594bf81cb19f',storagePath:root,runtimeDigest:'digest',gatewayV1Url:'http://127.0.0.1:9042/v1',key:'synthetic-test-key'};const put=async value=>writeFile(path.join(root,'credential-handoff.json'),JSON.stringify(value),{mode:0o600});try{await fn({root,values,secrets,input,put});}finally{await rm(root,{recursive:true,force:true});}}
test('connect stores in SecretStorage, deletes handoff, writes secret-free ack',async()=>fixture(async({root,values,secrets,input,put})=>{await put(input);assert.equal(await consumeHandoff(root,'digest',secrets),'connect');assert.ok(values.get(SECRET_NAME).includes(input.key));await assert.rejects(readFile(path.join(root,'credential-handoff.json')));const ack=JSON.parse(await readFile(path.join(root,'activation.json')));assert.equal(ack.connectionId,input.connectionId);assert.equal(ack.status,'connected');assert.ok(!JSON.stringify(ack).includes(input.key));}));
test('SecretStorage failure retains claim for crash-safe recovery',async()=>fixture(async({root,values,secrets,input,put})=>{await put(input);await assert.rejects(consumeHandoff(root,'digest',{async store(){throw new Error('fixture failure');}}));assert.ok(await readFile(path.join(root,'credential-handoff.claimed.json')));assert.equal(await consumeHandoff(root,'digest',secrets),'connect');assert.ok(values.has(SECRET_NAME));}));
test('wrong Profile/digest/malformed handoff never stores Key',async()=>fixture(async({root,values,secrets,input,put})=>{await put({...input,storagePath:root+'other'});await assert.rejects(consumeHandoff(root,'digest',secrets));assert.equal(values.size,0);}));
test('disconnect acknowledgment follows secret deletion',async()=>fixture(async({root,values,secrets,input,put})=>{values.set(SECRET_NAME,'old');await put({...input,operation:'disconnect'});assert.equal(await consumeHandoff(root,'digest',secrets),'disconnect');assert.equal(values.size,0);assert.equal(JSON.parse(await readFile(path.join(root,'activation.json'))).status,'disconnected');}));
test('new reconnect during SecretStorage write survives the old claim',async()=>fixture(async({root,values,secrets,input,put})=>{await put(input);const newer={...input,connectionId:'c8d9d8d1-053c-4c5e-9710-0742c9ac0561',key:'new-key'};await consumeHandoff(root,'digest',{async store(k,v){values.set(k,v);await put(newer);}});assert.equal(JSON.parse(await readFile(path.join(root,'credential-handoff.json'))).key,'new-key');await consumeHandoff(root,'digest',secrets);assert.equal(JSON.parse(values.get(SECRET_NAME)).key,'new-key');}));
test('link handoff is refused',async()=>fixture(async({root,values,secrets,input})=>{const target=path.join(root,'foreign.json');await writeFile(target,JSON.stringify(input),{mode:0o600});try{await symlink(target,path.join(root,'credential-handoff.json'));}catch(e){if(e.code==='EPERM')return;throw e;}await assert.rejects(consumeHandoff(root,'digest',secrets));assert.equal(values.size,0);}));
test('nonprivate Unix handoff is refused',async()=>fixture(async({root,secrets,input,put})=>{if(process.platform==='win32')return;await put(input);await chmod(path.join(root,'credential-handoff.json'),0o644);await assert.rejects(consumeHandoff(root,'digest',secrets));}));
