import test from 'node:test';import assert from 'node:assert/strict';import http from 'node:http';
import {OcgProvider,convertMessages,countTokens} from '../src/provider.mjs';import {projectCatalog,gatewayUrl} from '../src/catalog.mjs';
class Text{constructor(value){this.value=value;}}class Call{constructor(callId,name,input){Object.assign(this,{callId,name,input});}}class Result{constructor(callId,content){Object.assign(this,{callId,content});}}class Data{constructor(data,mimeType){Object.assign(this,{data,mimeType});}}class Emitter{event=()=>({dispose(){}});fire(){}dispose(){}}
const v={LanguageModelTextPart:Text,LanguageModelToolCallPart:Call,LanguageModelToolResultPart:Result,LanguageModelDataPart:Data,EventEmitter:Emitter,LanguageModelChatMessageRole:{User:1,Assistant:2,System:3},LanguageModelChatToolMode:{Required:2}};
const token={isCancellationRequested:false,onCancellationRequested(){return{dispose(){}};}};
function row(protocol='chat_completions',extra={}){return{id:'private-local-test',ocg:{schemaVersion:2,contextWindow:131072,maxOutputTokens:8192,toolCalling:true,inputModalities:['text','image'],protocols:{preferred:protocol,supported:[protocol]},...extra}};}
function events(protocol){
 if(protocol==='chat_completions')return[{choices:[{delta:{role:'assistant',content:'你好'},index:0}]},{choices:[{delta:{},finish_reason:'stop',index:0}],usage:{prompt_tokens:3,completion_tokens:2,total_tokens:5}},'[DONE]'];
 if(protocol==='responses')return[
 {type:'response.created',response:{id:'resp_1',model:'private-local-test',status:'in_progress',output:[],usage:null}},
 {type:'response.output_item.added',output_index:0,item:{type:'message',id:'msg_1',role:'assistant',content:[],status:'in_progress'}},
 {type:'response.content_part.added',output_index:0,content_index:0,item_id:'msg_1',part:{type:'output_text',text:'',annotations:[]}},
 {type:'response.output_text.delta',output_index:0,content_index:0,item_id:'msg_1',delta:'你好'},
 {type:'response.output_item.done',output_index:0,item:{type:'message',id:'msg_1',role:'assistant',content:[{type:'output_text',text:'你好',annotations:[]}],status:'completed'}},
 {type:'response.completed',response:{id:'resp_1',model:'private-local-test',status:'completed',output:[],usage:{input_tokens:3,output_tokens:2,total_tokens:5,input_tokens_details:{cached_tokens:0},output_tokens_details:{reasoning_tokens:0}}}}];
 return[{type:'message_start',message:{id:'msg_1',type:'message',role:'assistant',model:'private-local-test',content:[],stop_reason:null,stop_sequence:null,usage:{input_tokens:3,output_tokens:0}}},{type:'content_block_start',index:0,content_block:{type:'text',text:''}},{type:'content_block_delta',index:0,delta:{type:'text_delta',text:'你好'}},{type:'content_block_stop',index:0},{type:'message_delta',delta:{stop_reason:'end_turn',stop_sequence:null},usage:{output_tokens:2}},{type:'message_stop'}];
}
async function server(protocol,fn){const observed=[];let catalog=[row(protocol)];const server=http.createServer(async(req,res)=>{if(req.url==='/v1/models'){res.writeHead(200,{'content-type':'application/json'}).end(JSON.stringify({data:catalog}));return;}
 const chunks=[];for await(const c of req)chunks.push(c);observed.push({path:req.url,headers:req.headers,body:JSON.parse(Buffer.concat(chunks))});res.writeHead(200,{'content-type':'text/event-stream'});
 for(const event of events(protocol)){const data=Buffer.from(`${typeof event==='object'&&event.type?'event: '+event.type+'\n':''}data: ${typeof event==='string'?event:JSON.stringify(event)}\n\n`);for(let i=0;i<data.length;i+=7)res.write(data.subarray(i,i+7));}res.end();});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/v1`;try{await fn({observed,url,setCatalog:v=>catalog=v,server});}finally{server.closeAllConnections();await new Promise(r=>server.close(r));}}
for(const protocol of ['chat_completions','responses','messages'])test(`real SDK fragmented ${protocol} preserves system/images/tools and URL`,async()=>server(protocol,async({observed,url})=>{
 const provider=new OcgProvider(v,async()=>({key:'synthetic-ocg-secret',gatewayV1Url:url}));const [model]=await provider.provideLanguageModelChatInformation({silent:true},token);const parts=[];
 await provider.provideLanguageModelChatResponse(model,[{role:3,content:[new Text('Keep the system instruction')]},{role:1,content:[new Text('hello'),new Data(Uint8Array.from([1,2,3]),'image/png')]}],{tools:[{name:'tool_fixture',description:'a test',inputSchema:{type:'object',properties:{}}}]},{report:p=>parts.push(p)},token);
 assert.equal(parts.map(p=>p.value??'').join(''),'你好');assert.equal(observed.length,1);assert.equal(observed[0].path.split('?')[0],{chat_completions:'/v1/chat/completions',responses:'/v1/responses',messages:'/v1/messages'}[protocol]);assert.equal(observed[0].headers.authorization,'Bearer synthetic-ocg-secret');assert.ok(JSON.stringify(observed[0].body).includes('Keep the system instruction'));assert.ok(JSON.stringify(observed[0].body).includes('AQID'));assert.ok(JSON.stringify(observed[0].body).includes('tool_fixture'));provider.dispose();
}));
test('authoritative per-model limits and incomplete metadata stay explicit',()=>{const result=projectCatalog({data:[row(),{...row(),id:'missing',ocg:{...row().ocg,contextWindow:null}}]},'http://127.0.0.1/v1');assert.equal(result.models[0].maxInputTokens,122880);assert.deepEqual(result.metadataMissing,['missing']);});
test('public aliases remain distinguishable when upstream display names match',()=>{
 const names=['alias-one','alias-two'];
 const result=projectCatalog({data:names.map(id=>({...row('chat_completions',{name:'Shared upstream display name'}),id}))},'http://127.0.0.1/v1');
 assert.deepEqual(result.models.map(m=>m.name),names);
 for(const m of result.models){assert.equal(m.id,m.name);assert.equal(m.apiModel.id,m.id);assert.equal(m.apiModel.name,m.id);}
});
test('schema/profile/duplicate protocol metadata fails closed',()=>{for(const data of [[row(),row()],[row('other')],[row('responses',{schemaVersion:1})]])assert.throws(()=>projectCatalog({data},'http://127.0.0.1/v1'));});
test('removed and changed models cannot send on stale picker state',async()=>server('chat_completions',async({url,setCatalog,observed})=>{const p=new OcgProvider(v,async()=>({key:'test',gatewayV1Url:url}));const [m]=await p.provideLanguageModelChatInformation({},token);setCatalog([]);await assert.rejects(p.provideLanguageModelChatResponse(m,[{role:1,content:[new Text('hi')]}],{},{report(){}},token));assert.equal(observed.length,0);setCatalog([row('chat_completions',{contextWindow:32000})]);await assert.rejects(p.provideLanguageModelChatResponse(m,[],{},{report(){}},token));assert.equal(observed.length,0);p.dispose();}));
test('tool result identity preserved and unknown parts rejected',()=>{const m=projectCatalog({data:[row()]},'http://127.0.0.1/v1').models[0];const c=convertMessages(v,[{role:2,content:[new Call('call_1','tool_fixture',{a:1})]},{role:1,content:[new Result('call_1',[new Text('result')])]}],m);assert.equal(c.messages[1].toolCallId,'call_1');assert.equal(c.messages[1].toolName,'tool_fixture');assert.throws(()=>convertMessages(v,[{role:1,content:[{}]}],m));assert.throws(()=>convertMessages(v,[{role:1,content:[new Result('unknown',[])]}],m));});
test('token counting handles Chinese and structured tools',()=>{assert.ok(countTokens('中华人民共和国')>0);assert.ok(countTokens({content:[new Call('c','x',{value:'测试'})]})>8);assert.ok(countTokens({content:[new Data(new Uint8Array(3),'image/png')]})>=4096);});
test('unsafe URL and redirect auth destinations rejected',()=>{for(const url of ['http://example.com/v1','http://127.evil.example/v1','https://u:p@example.com/v1','https://example.com/v1?q=secret'])assert.throws(()=>gatewayUrl(url));});
test('upstream errors never echo a secret',async()=>{const secret='never-echo-this-key';const p=new OcgProvider(v,async()=>({key:secret,gatewayV1Url:'http://127.0.0.1/v1'}),async()=>{},async()=>new Response(secret,{status:401}));await assert.rejects(p.provideLanguageModelChatResponse({id:'x'},[],{},{report(){}},token),e=>!e.message.includes(secret));p.dispose();});
test('already cancelled request cannot reach the model',async()=>server('chat_completions',async({url,observed})=>{const p=new OcgProvider(v,async()=>({key:'test',gatewayV1Url:url}));const [m]=await p.provideLanguageModelChatInformation({},token);await assert.rejects(p.provideLanguageModelChatResponse(m,[],{},{report(){}},{...token,isCancellationRequested:true}));assert.equal(observed.length,0);p.dispose();}));

function toolEvents(protocol){
 if(protocol==='chat_completions')return [{choices:[{index:0,delta:{role:'assistant',tool_calls:[{index:0,id:'call_1',type:'function',function:{name:'tool_fixture',arguments:'{\"value\":'}}]}}]},{choices:[{index:0,delta:{tool_calls:[{index:0,function:{arguments:'1}'}}]},finish_reason:'tool_calls'}]},'[DONE]'];
 if(protocol==='responses')return [{type:'response.created',response:{id:'resp_tool',status:'in_progress',output:[]}},{type:'response.output_item.added',output_index:0,item:{type:'function_call',id:'fc_1',call_id:'call_1',name:'tool_fixture',arguments:''}},{type:'response.function_call_arguments.delta',item_id:'fc_1',output_index:0,delta:'{\"value\":1}'},{type:'response.output_item.done',output_index:0,item:{type:'function_call',id:'fc_1',call_id:'call_1',name:'tool_fixture',arguments:'{\"value\":1}',status:'completed'}},{type:'response.completed',response:{id:'resp_tool',status:'completed',output:[],usage:{input_tokens:1,output_tokens:1,total_tokens:2}}}];
 return [{type:'message_start',message:{id:'m',type:'message',role:'assistant',content:[],stop_reason:null,usage:{input_tokens:1,output_tokens:0}}},{type:'content_block_start',index:0,content_block:{type:'thinking',thinking:''}},{type:'content_block_delta',index:0,delta:{type:'thinking_delta',thinking:'private reasoning'}},{type:'content_block_delta',index:0,delta:{type:'signature_delta',signature:'signed-test-opaque'}},{type:'content_block_stop',index:0},{type:'content_block_start',index:1,content_block:{type:'tool_use',id:'call_1',name:'tool_fixture',input:{}}},{type:'content_block_delta',index:1,delta:{type:'input_json_delta',partial_json:'{\"value\":1}'}},{type:'content_block_stop',index:1},{type:'message_delta',delta:{stop_reason:'tool_use'},usage:{output_tokens:1}},{type:'message_stop'}];
}
for(const protocol of ['chat_completions','responses','messages'])test(`tool round trip and hidden reasoning ${protocol}`,async()=>{
 let requests=[];const server=http.createServer(async(req,res)=>{if(req.url==='/v1/models'){res.writeHead(200,{'content-type':'application/json'}).end(JSON.stringify({data:[row(protocol,{reasoning:true})]}));return;}const body=[];for await(const c of req)body.push(c);requests.push(JSON.parse(Buffer.concat(body)));res.writeHead(200,{'content-type':'text/event-stream'});for(const e of requests.length===1?toolEvents(protocol):events(protocol)){const b=Buffer.from(`${typeof e==='object'&&e.type?'event: '+e.type+'\n':''}data: ${typeof e==='string'?e:JSON.stringify(e)}\n\n`);for(let i=0;i<b.length;i+=9)res.write(b.subarray(i,i+9));}res.end();});await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const p=new OcgProvider(v,async()=>({key:'fixture',gatewayV1Url:`http://127.0.0.1:${server.address().port}/v1`}));try{const [model]=await p.provideLanguageModelChatInformation({},token);const parts=[],tools=[{name:'tool_fixture',description:'test',inputSchema:{type:'object',properties:{value:{type:'number'}}}}];const messages=[{role:1,content:[new Text('use tool')]}];await p.provideLanguageModelChatResponse(model,messages,{tools,toolMode:2},{report:x=>parts.push(x)},token);const call=parts.find(x=>x instanceof Call);assert.ok(call);assert.deepEqual(call.input,{value:1});assert.equal(parts.some(x=>x.value?.includes('private reasoning')),false);
 await p.provideLanguageModelChatResponse(model,[...messages,{role:2,content:[call]},{role:1,content:[new Result(call.callId,[new Text('TOOL-RESULT')])]}],{tools},{report(){}},token);assert.equal(requests.length,2);assert.ok(JSON.stringify(requests[1]).includes('TOOL-RESULT'));if(protocol==='messages')assert.ok(JSON.stringify(requests[1]).includes('signed-test-opaque'));p.clear();assert.equal(p.replay.size,0);
 }finally{p.dispose();server.closeAllConnections();await new Promise(r=>server.close(r));}
});
test('cancellation after streamed text stops an in-flight request',async()=>{let cancel=()=>{};const server=http.createServer(async(req,res)=>{if(req.url==='/v1/models'){res.writeHead(200,{'content-type':'application/json'}).end(JSON.stringify({data:[row()]}));return;}for await(const c of req){}res.writeHead(200,{'content-type':'text/event-stream'});res.write('data: '+JSON.stringify({choices:[{index:0,delta:{role:'assistant',content:'first'}}]})+'\n\n');});await new Promise(r=>server.listen(0,'127.0.0.1',r));const p=new OcgProvider(v,async()=>({key:'test',gatewayV1Url:`http://127.0.0.1:${server.address().port}/v1`}));try{const [model]=await p.provideLanguageModelChatInformation({},token);await assert.rejects(p.provideLanguageModelChatResponse(model,[{role:1,content:[new Text('hi')]}],{},{report(){cancel();}},{isCancellationRequested:false,onCancellationRequested(fn){cancel=fn;return{dispose(){}};}}));assert.equal(p.controllers.size,0);}finally{p.dispose();server.closeAllConnections();await new Promise(r=>server.close(r));}});

test('literal tokenizer syntax in source code is ordinary text',()=>{assert.ok(countTokens('<|endoftext|>')>1);});

test('mixed tool results preserve accompanying user context',()=>{
 const [model]=projectCatalog({data:[row()]}).models;
 const c=convertMessages(v,[{role:2,content:[new Call('mixed','fixture',{})]},{role:1,content:[new Text('additional context'),new Result('mixed',[new Text('result')])]}],model);
 assert.equal(c.messages[1].role,'toolResult');assert.equal(c.messages[2].content[0].text,'additional context');
});
for(const protocol of ['chat_completions','responses'])test(`declared reasoning wire ${protocol}`,async()=>server(protocol,async({url,observed,setCatalog})=>{
 setCatalog([row(protocol,{reasoning:true,reasoningEfforts:{deep:'high'},parallelToolCalls:true})]);
 const p=new OcgProvider(v,async()=>({key:'fixture',gatewayV1Url:url}),async()=>{},fetch,()=> 'deep');
 try{const [model]=await p.provideLanguageModelChatInformation({},token);await p.provideLanguageModelChatResponse(model,[{role:1,content:[new Text('hello')]}],{},{report(){}},token);
 assert.equal(protocol==='responses'?observed[0].body.reasoning.effort:observed[0].body.reasoning_effort,'high');assert.equal('parallel_tool_calls' in observed[0].body,false);
 }finally{p.dispose();}
}));

test('untrusted error with a friendly prefix cannot bypass redaction',async()=>server('chat_completions',async({url})=>{
 const p=new OcgProvider(v,async()=>({key:'fixture',gatewayV1Url:url}),async()=>{},async(u,init)=>{if(String(u).endsWith('/models'))return fetch(u,init);throw new Error('This model exposed never-echo-this-key');});
 try{const [model]=await p.provideLanguageModelChatInformation({},token);await assert.rejects(p.provideLanguageModelChatResponse(model,[],{},{report(){}},token),e=>!e.message.includes('never-echo-this-key'));}finally{p.dispose();}
}));
