//! Compatibility facade for [`ocg_domain::ids`].
//!
//! Public items match the historical `ocg_core::kernel::ids` surface.

pub use ocg_domain::ids::{
    COMMAND_CODE_GOAT_DEEPSEEK_V4_FLASH_ALIAS, COMMAND_CODE_GOAT_DEEPSEEK_V4_FLASH_UPSTREAM,
    COMMAND_CODE_PROVIDER_ID, CPA_ACCOUNT_ID, CPA_ACCOUNT_NAME, CPA_PROVIDER_ID,
    CUSTOM_PROVIDER_ID, DEFAULT_ACCOUNT_TEST_MODEL, KIMI_PROVIDER_ID, MINIMAX_PROVIDER_ID,
    OLLAMA_CLOUD_BASE_URL, OLLAMA_CLOUD_CHAT_COMPLETIONS_PATH, OLLAMA_CLOUD_MODELS_PATH,
    OLLAMA_CLOUD_PRICING_URL, OLLAMA_PROVIDER_ID, OPENCODE_PROVIDER_ID,
    OPENCODE_ZEN_FREE_PROVIDER_ID, PRIMARY_KEY_ID, PRIMARY_KEY_NAME, ZEN_FREE_ACCOUNT_ID,
    ZEN_FREE_ACCOUNT_NAME, custom_model_id_matches, is_free_model, model_identity_key,
    normalize_model_name,
};
